/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_demo_One */

#ifndef _Included_com_ndk_demo_One
#define _Included_com_ndk_demo_One
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_demo_One
 * Method:    stringFromOneLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ndk_demo_One_stringFromOneLibrary
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
