/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_demo_Two */

#ifndef _Included_com_ndk_demo_Two
#define _Included_com_ndk_demo_Two
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ndk_demo_Two
 * Method:    stringFromOneLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ndk_demo_Two_stringFromOneLibrary
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
